[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
unsound = "deny"
yanked = "warn"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSL-1.0",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "0BSD",
]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
